import { Router } from 'express';
import { getOnboardingStateHandler } from '../services/onboarding/getState';
import { saveOnboardingStep } from '../services/onboarding/saveStep';
import { completeOnboarding } from '../services/onboarding/complete';
import { getOnboardingBanks } from '../services/onboarding/getBanks';
import { resolveOnboardingBankAccount } from '../services/onboarding/resolveBankAccount';
export const onboardingRouter = Router();
onboardingRouter.get('/banks', getOnboardingBanks);
onboardingRouter.get('/banks/resolve', resolveOnboardingBankAccount);
onboardingRouter.post('/state', getOnboardingStateHandler);
onboardingRouter.post('/step/:step', saveOnboardingStep);
onboardingRouter.post('/complete', completeOnboarding);
