apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce
  namespace: corelabs
  labels:
    app: e-commerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-commerce
  strategy: {}
  template:
    metadata:
      labels:
        app: e-commerce
    spec:
      containers:
      - image: etre548/ecommerce:latest
        name: ecommerce
        imagePullPolicy: Always
        ports:
        - containerPort: 4004
        envFrom:
        - secretRef:
            name: e-commerce-secrets
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: "1"
            memory: 1Gi
