apiVersion: v1
kind: Service
metadata:
  name: e-commerce
  namespace: corelabs
  labels:
    app: e-commerce
spec:
  type: NodePort
  selector:
    app: e-commerce
  ports:
    - name: http
      port: 4004
      targetPort: 4004
      protocol: TCP
status:
  loadBalancer: {}
