export const HIGHLIGHT_CLIP_PRE_ROLL_SECONDS = 5;
export const HIGHLIGHT_CLIP_DURATION_SECONDS = 15;
export const HIGHLIGHT_MARKER_DEDUPE_SECONDS = 20;
export const HIGHLIGHT_MAX_CLIPS_PER_STREAM = 30;
