import { Router } from 'express';
import { authenticate } from '@core/middleware/rbac';
import { biometricRouter } from './biometric';
import { getSignupSettings } from '../services/signup-settings';
import { register } from '../services/register';
import { loginUser } from '../services/loginUser';
import { verify2fa } from '../services/verify2fa';
import { refresh } from '../services/refresh';
import { logout } from '../services/logout';
import { forgotPassword } from '../services/forgot-password';
import { verifyPasswordResetOtp } from '../services/verify-password-reset-otp';
import { resetPassword } from '../services/reset-password';
import { verifyEmail } from '../services/verify-email';
import { resendOTP } from '../services/resendOTP';
import { oauthProvider } from '../services/oauthProvider';
import { providerCallback } from '../services/providerCallback';
import { completeOAuthSignup } from '../services/complete-oauth-signup';
import { getRatesfromcache } from '../services/getRatesfromcache';
import { privyLogin } from '../services/privy/login';
export const authRouter = Router();
authRouter.use('/biometric', biometricRouter);
authRouter.get('/signup-settings', getSignupSettings);
authRouter.post('/register', register);
authRouter.post('/login', loginUser);
authRouter.post('/login/verify-2fa', verify2fa);
authRouter.post('/privy/login', privyLogin);
authRouter.post('/refresh', refresh);
authRouter.post('/logout', authenticate, logout);
authRouter.post('/forgot-password', forgotPassword);
authRouter.post('/verify-password-reset-otp', verifyPasswordResetOtp);
authRouter.post('/reset-password', resetPassword);
authRouter.post('/verify-email', verifyEmail);
authRouter.post('/resend-otp', resendOTP);
authRouter.get('/oauth/:provider', oauthProvider);
authRouter.get('/oauth/:provider/callback', providerCallback);
authRouter.post('/oauth/complete-signup', completeOAuthSignup);
authRouter.get('/rates', getRatesfromcache);
